# Generated by Django 3.1.3 on 2020-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201106_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='art_image',
            field=models.ImageField(upload_to='news/images'),
        ),
    ]
