# Generated by Django 3.1.3 on 2020-11-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201106_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='art_content',
        ),
    ]
