# Generated by Django 3.1.3 on 2020-11-06 15:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_articles_art_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='art_content',
            field=tinymce.models.HTMLField(default=' '),
        ),
    ]
