# Generated by Django 3.1.3 on 2020-11-06 15:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articles_art_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='art_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='art_image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
