# Generated by Django 3.1.3 on 2020-11-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201106_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt_id', models.IntegerField()),
                ('cmt_content', models.CharField(max_length=200)),
                ('cmt_name', models.CharField(max_length=30)),
                ('cmt_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.articles')),
            ],
        ),
    ]
