# Generated by Django 3.1.3 on 2020-11-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201107_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cmt_pk',
        ),
    ]
